name: Deploy to PROD

on:
  release:
    types:
      - published
  push:
    tags:
      - prod

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to PROD
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_PROD }}
      env: prod
    secrets:
      env_file: ${{ secrets.ENV_PROD }}
      cdk_env_file: ${{ secrets.CDK_ENV_PROD }}
