name: Deploy to QA

on:
  push:
    branches:
      - release/*
    tags:
      - qa

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to QA
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_QA }}
      env: qa
    secrets:
      env_file: ${{ secrets.ENV_QA }}
      cdk_env_file: ${{ secrets.CDK_ENV_QA }}
